# Generated by Django 4.2 on 2023-04-15 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField(max_length=10, unique=True)),
                ('employee_name', models.CharField(max_length=100)),
                ('employee_mobile', models.CharField(max_length=16)),
                ('employee_email', models.EmailField(blank=True, max_length=100, null=True)),
                ('salary', models.PositiveIntegerField(default=0, max_length=6)),
                ('Date_Of_Birth', models.DateField()),
                ('image_file', models.ImageField(upload_to='employee/images')),
                ('cv_file', models.FileField(upload_to='employee/docs')),
                ('joining_date', models.DateField()),
                ('employee_hight', models.DecimalField(decimal_places=1, max_digits=3)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=6)),
                ('is_positive', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
